#!/usr/bin/env bash
# Configures the container to run nginx as nginx user.
pkill -f apache2
sed -i s/80/8080/g /etc/nginx/sites-available/default
chmod -R 666 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
